reporter: "xcode"

disabled_rules:
  - blanket_disable_command
  - line_length
  - function_parameter_count
  - type_name
  - nesting
  - xctfail_message

opt_in_rules:
  - force_unwrapping
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace
  - weak_delegate

superfluous_disable_command:
  severity: warning

large_tuple: 3

overridden_super_call:
  severity: error

unused_optional_binding:
  severity: error

force_unwrapping: error
force_cast: error
force_try: error
weak_delegate: error
