reporter: "xcode"

disabled_rules:
  - line_length
  - function_parameter_count
  - type_name
  - nesting
  - xctfail_message

large_tuple: 3

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 600

function_body_length:
  warning: 50
  error: 60

overridden_super_call:
  severity: error

unused_optional_binding:
  severity: error

force_unwrapping: error
force_cast: error
